create table data (
	id IDENTITY PRIMARY KEY auto_increment,
	url varchar(2000) not null,
	img_url varchar(2000) null,
	name varchar(500) not null,
	description text null,
	price varchar(20) null,
	stock varchar(100) null,
	origin_stock varchar(100) null,
	valid_until varchar(100) null,
	FAIL_COUNT int null,
	ENABLE_NOTIFICATION char(5) not null,
	MESSAGE_ID varchar(150) null,
	CHAT_ID varchar(150) null,
    BGG_ID int null,
    BGG_RATING varchar(20) null,
    BGG_WISHING int null,
    BGG_WANTING int null,
    BGG_LINK varchar(2000) null,
    ENABLE_BGG char(5) not null,
    BEST_PRICE varchar(20) null,
    BEST_PRICE_URL varchar(2000) null,
    ENABLE_BEST_PRICE char(5) not null,
    CRAWLER_NAME varchar(50) not null,
	create_date timestamp not null,
	update_date timestamp not null
);