create table data (
	ID IDENTITY PRIMARY KEY auto_increment,
	URL varchar(2000) not null,
	IMG_URL varchar(2000) null,
	NAME varchar(500) not null,
	DESCRIPTION text null,
	PRICE varchar(20) null,
	STOCK varchar(150) null,
	VALID_UNTIL varchar(100) null,
	ENABLE_NOTIFICATION char(5) not null,
	MESSAGE_ID varchar(150) null,
	CHAT_ID varchar(150) null,
	NOTIFICATION_FAIL_COUNT int not null,
    BGG_ID int null,
    BGG_RATING varchar(20) null,
    BGG_WISHING int null,
    BGG_WANTING int null,
    BGG_LINK varchar(2000) null,
    ENABLE_BGG char(5) not null,
    BGG_FAIL_COUNT int not null,
    BEST_PRICE varchar(20) null,
    BEST_PRICE_URL varchar(2000) null,
    ENABLE_BEST_PRICE char(5) not null,
    BEST_PRICE_FAIL_COUNT int not null,
    CRAWLER_NAME varchar(50) not null,
	CREATE_DATE timestamp not null,
	UPDATE_DATE timestamp not null
);